#!/usr/bin/env python3
"""
Generate all wg-easy-gluetun config files from config.yaml + templates/.

Usage:
  python scripts/generate_configs.py             # generate all files
  python scripts/generate_configs.py --dry-run   # preview without writing
  python scripts/generate_configs.py --config /path/to/config.yaml

Template syntax  (custom delimiters — avoids conflicts with wg-easy {{}} and shell ${}):
  [[ var ]]        variable output
  [% if / for %]   control flow
  [# comment #]    comment (stripped from output)
"""

import sys
import argparse
from pathlib import Path

try:
    import yaml
except ImportError:
    print("Error: PyYAML is required.  pip install pyyaml")
    sys.exit(1)

try:
    import jinja2
except ImportError:
    print("Error: Jinja2 is required.  pip install jinja2")
    sys.exit(1)

ROOT          = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = ROOT / "templates"
NOTE          = "AUTO-GENERATED by scripts/generate_configs.py — edit templates/ and config.yaml instead"

# Custom delimiters so templates coexist with:
#   wg-easy runtime templates  {{port}}, {{ipv4Cidr}}, {{ipv6Cidr}}
#   shell variables             $VAR, ${VAR:-}
#   JSON / awk braces           {}
jinja_env = jinja2.Environment(
    loader=jinja2.FileSystemLoader(str(TEMPLATES_DIR)),
    variable_start_string="[[",
    variable_end_string="]]",
    block_start_string="[%",
    block_end_string="%]",
    comment_start_string="[#",
    comment_end_string="#]",
    keep_trailing_newline=True,
    trim_blocks=True,
    lstrip_blocks=True,
    undefined=jinja2.StrictUndefined,
)
jinja_env.filters["bool_str"] = lambda v: "true" if v else "false"


# ── config loading ─────────────────────────────────────────────────────────────

def load_config(path: Path) -> dict:
    with open(path) as f:
        return yaml.safe_load(f)


def validate(cfg: dict) -> list[str]:
    warnings = []
    wg = cfg["vpn"]["wireguard"]
    if not wg.get("private_key"):
        warnings.append("vpn.wireguard.private_key is empty")
    if not wg.get("addresses"):
        warnings.append("vpn.wireguard.addresses is empty")
    if not cfg["wg_easy"]["init"].get("password"):
        warnings.append("wg_easy.init.password is empty")
    if not cfg["singbox"].get("clash_api_secret"):
        warnings.append("singbox.clash_api_secret is empty")
    return warnings


def build_context(cfg: dict) -> dict:
    """Flatten config.yaml into a template context."""
    svc = cfg["network"]["services"]
    sb  = cfg["singbox"]
    vpn = cfg["vpn"]
    wg  = cfg["wg_easy"]

    bypass_sets = sb.get("bypass_rule_sets", [])
    extra_sets  = sb.get("extra_rule_sets",  [])

    return {
        # Top-level config sections (accessible as e.g. [[ vpn.wireguard.private_key ]])
        "network":     cfg["network"],
        "vpn":         vpn,
        "wg_easy":     wg,
        "singbox":     sb,
        "adguardhome": cfg["adguardhome"],
        # Shorthand aliases for frequently used IPs
        "svc":            svc,
        "wg_easy_ip_esc": svc["wg_easy"]["ipv4"].replace(".", r"\."),
        "adguard_ipv4":   svc["adguardhome"]["ipv4"],
        "adguard_ipv6":   svc["adguardhome"]["ipv6"],
        "singbox_ipv4":   svc["singbox"]["ipv4"],
        "singbox_ipv6":   svc["singbox"]["ipv6"],
        "gluetun_ipv4":   svc["gluetun"]["ipv4"],
        "gluetun_ipv6":   svc["gluetun"]["ipv6"],
        # sing-box rule sets
        "bypass_tags":   [rs["tag"] for rs in bypass_sets],
        "all_rule_sets": bypass_sets + extra_sets,
        # wg-easy direct-subnet bypass
        "direct_subnets":      wg.get("direct_subnets",      []),
        "direct_subnets_ipv6": wg.get("direct_subnets_ipv6", []),
        # Misc
        "firewall_subnets_str": ",".join(vpn.get("firewall_outbound_subnets", [])),
        "NOTE": NOTE,
    }


# ── rendering + writing ────────────────────────────────────────────────────────

def render(template_name: str, ctx: dict, extra: dict | None = None) -> str:
    t = jinja_env.get_template(template_name)
    return t.render({**ctx, **(extra or {})})


def write_file(path: Path, content: str, dry_run: bool) -> None:
    rel = path.relative_to(ROOT)
    if dry_run:
        print(f"  [dry-run] {rel}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"  wrote     {rel}")


# (template relative to templates/, destination relative to project root, extra context)
TARGETS: list[tuple[str, str, dict | None]] = [
    ("docker-compose.yml.j2",           "runtime/docker-compose.yml",                None),
    ("env.j2",                          "runtime/.env",                              None),
    ("hooks/wg-hook.txt.j2",            "runtime/conf/hooks/wg-post-up.txt",        {"action": "add"}),
    ("hooks/wg-hook.txt.j2",            "runtime/conf/hooks/wg-post-down.txt",      {"action": "del"}),
    ("iptables/post-rules.txt.j2",      "runtime/conf/iptables/post-rules.txt",     None),
    ("sing-box/config.json.j2",         "runtime/conf/sing-box/config.json",        None),
    ("sing-box/entrypoint.sh.j2",       "runtime/conf/sing-box/entrypoint.sh",      None),
    ("adguardhome/AdGuardHome.yaml.j2", "runtime/conf/adguardhome/AdGuardHome.yaml",None),
]


# ── main ───────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--config",  default=str(ROOT / "config.yaml"),
                        help="Path to config.yaml (default: <project-root>/config.yaml)")
    parser.add_argument("--dry-run", action="store_true",
                        help="Print what would be written without actually writing")
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"Error: config file not found: {config_path}")
        sys.exit(1)

    cfg = load_config(config_path)

    warnings = validate(cfg)
    if warnings:
        print("Warnings:")
        for w in warnings:
            print(f"  ! {w}")
        print()

    ctx = build_context(cfg)

    print("Dry-run:" if args.dry_run else "Generating:")
    for tmpl, dest_rel, extra in TARGETS:
        content = render(tmpl, ctx, extra)
        write_file(ROOT / dest_rel, content, dry_run=args.dry_run)

    if not args.dry_run:
        (ROOT / "runtime/conf/sing-box/entrypoint.sh").chmod(0o755)
        print()
        print("Done.  Restart the stack to apply changes:")
        print("  docker compose up -d")


if __name__ == "__main__":
    main()
